class CreateGitValues < ActiveRecord::Migration
  def self.up
    create_table :git_values, :force => true do |t|
      t.float :min_measure1
      t.float :min_measure2
      t.float :min_measure3
      t.float :min_measure4
      t.float :min_measure5
      t.float :min_measure6
      t.float :min_measure7
      t.float :min_measure8
      t.float :min_measure9
      t.float :min_measure10
      t.float :min_measure11
      t.float :min_measure12
      t.float :min_measure13
      t.float :min_measure14
      t.float :min_measure15
      t.float :min_measure16
      t.float :min_measure17
      t.float :min_measure18
      t.float :min_measure19
      t.float :min_measure20
      t.float :min_measure21
      t.float :min_measure22
      t.float :min_measure23
      t.float :min_measure24
      t.float :min_measure25
      t.float :min_measure26
      t.float :min_measure27
      t.float :min_measure28
      t.float :min_measure29
      t.float :min_measure30
      t.float :max_measure1
      t.float :max_measure2
      t.float :max_measure3
      t.float :max_measure4
      t.float :max_measure5
      t.float :max_measure6
      t.float :max_measure7
      t.float :max_measure8
      t.float :max_measure9
      t.float :max_measure10
      t.float :max_measure11
      t.float :max_measure12
      t.float :max_measure13
      t.float :max_measure14
      t.float :max_measure15
      t.float :max_measure16
      t.float :max_measure17
      t.float :max_measure18
      t.float :max_measure19
      t.float :max_measure20
      t.float :max_measure21
      t.float :max_measure22
      t.float :max_measure23
      t.float :max_measure24
      t.float :max_measure25
      t.float :max_measure26
      t.float :max_measure27
      t.float :max_measure28
      t.float :max_measure29
      t.float :max_measure30
      t.float :submax_measure1
      t.float :submax_measure2
      t.float :submax_measure3
      t.float :submax_measure4
      t.float :submax_measure5
      t.float :submax_measure6
      t.float :submax_measure7
      t.float :submax_measure8
      t.float :submax_measure9
      t.float :submax_measure10
      t.float :submax_measure11
      t.float :submax_measure12
      t.float :submax_measure13
      t.float :submax_measure14
      t.float :submax_measure15
      t.float :submax_measure16
      t.float :submax_measure17
      t.float :submax_measure18
      t.float :submax_measure19
      t.float :submax_measure20
      t.float :submax_measure21
      t.float :submax_measure22
      t.float :submax_measure23
      t.float :submax_measure24
      t.float :submax_measure25
      t.float :submax_measure26
      t.float :submax_measure27
      t.float :submax_measure28
      t.float :submax_measure29
      t.float :submax_measure30
    end
  end

  def self.down
    drop_table :git_values
  end
end
